FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:223 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x8004213f73 0x800420a32b 0x8004218a5e 0x800420756e
Translation of call stack:
0x0000008004213f73: debug_panic (lib/kernel/debug.c:32)
0x000000800420a32b: lock_release (threads/synch.c:225)
0x0000008004218a5e: acquire1_thread_func (tests/threads/priority-donate-one.c:53)
0x000000800420756e: kernel_thread (threads/thread.c:450)
